input: file:/I:/2022/IntelliJ Workspace/batch-example/src/main/resources/users.csv
spring:
  batch:
    initialize-schema: always
    job:
      enabled: false
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/abc
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update